// Публичный API UI-kit (business-agnostic): импорт через '@/shared/ui'.
export { IconSymbol } from './icon-symbol';
export { HapticTab } from './haptic-tab';
export { Text, type ITextProps } from './text';
export { Divider, type IDividerProps } from './divider';
export { Card, type ICardProps } from './card';
export { Screen, type IScreenProps } from './screen';
export { Button, type IButtonProps, type IButtonVariant, type IButtonSize } from './button';
export { Badge, type IBadgeProps, type IBadgeVariant } from './badge';
export { Chip, type IChipProps } from './chip';
export { Input, type IInputProps } from './input';
export { Skeleton, type ISkeletonProps } from './skeleton';
export { EmptyState, type IEmptyStateProps } from './empty-state';
export { ErrorState, type IErrorStateProps } from './error-state';
export { Toast, type IToastProps, type IToastVariant } from './toast';
export { IconButton, type IIconButtonProps } from './icon-button';
export { SearchInput, type ISearchInputProps } from './search-input';
export { DiagnosticCard, type IDiagnosticCardProps } from './diagnostic-card';
export { DiagnosticRow, type IDiagnosticRowProps } from './diagnostic-row';
export { ScreenHeader, type IScreenHeaderProps } from './screen-header';
